### ISSUE TITLE
你好 卡在第二个 爱心了 heart 2 

### ISSUE THREAD

**Issue by yolio2003** [allenwong/MakeIconsWithSketch#1]
两个矩形都摆好了，但是 edit 后 还是只选中了一个矩形的 path 怎么也不会弄了， 特来麻烦你一下哦！

如何才能像 gif 里面一样 框选 4 个顶部节点？ 我框选的时候 是斜 45度，而且只能选单独一边的矩形

**Comment by allenwong** [comment]
首先 Sketch 更新到最新版本；
其次你再图层那边要先选中两个矩形，然后再点 Edit，在去选四个节点；

**Comment by yolio2003** [comment]
非常感谢 确实是版本问题 搞定了！
