### ISSUE TITLE
如果能把整个sketch的界面给录上就好了

### ISSUE THREAD

**Issue by fanchangyong** [allenwong/MakeIconsWithSketch#3]
你好，首先非常喜欢这个项目，但是对于初学者来说，只看这样的gif还是并不知道具体在sketch中是怎么操作的。
所以为什么不把整个sketch的界面给录上呢，能让人看清楚是怎么操作的。

**Comment by allenwong** [comment]
因为当初面向的不是初学者，而且全屏录上操作其实非常快，也看的不太清楚。
